SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `imobiliaria_if`.`tipo_mensagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo_mensagem_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_mensagem_menagem_idx` (`tipo_mensagem_id` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_mensagem_tipo_mensagem`
    FOREIGN KEY (`tipo_mensagem_id`)
    REFERENCES `imobiliaria_if`.`tipo_mensagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE IF NOT EXISTS `imobiliaria_if`.`contato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `mensagem` VARCHAR(300) NOT NULL,
  `tipo_mensagem` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contato_tipo_mensagem_idx` (`tipo_mensagem` ASC) VISIBLE,
  CONSTRAINT `fk_contato_tipo_mensagem`
    FOREIGN KEY (`tipo_mensagem`)
    REFERENCES `imobiliaria_if`.`tipo_mensagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;